[tool.isort]
py_version=311
skip = [".gitignore", ".venv/"]

[tool.black]
force-exclude = '''
/(
\.git
| \.mypy_cache
| \.venv
| _build
| build
| dist
)/
'''

[tool.pytest.ini_options]
markers = [
    "calls"
]